### ISSUE TITLE
[spirv] DXC crashes when compiling using -Zi and a header is not found

### ISSUE THREAD

**Issue by tafuri** [Microsoft/DirectXShaderCompiler#1860]
Compiling the following shader:
```hlsl
#include <missing.h>
[numthreads(8, 8, 1)]
void main() {}
```

Using the following commandline `dxc -Zi -Tcs_6_0 -spirv shader.prog` will crash with the following stacktrace:
```
#0  0x000000000044ac8b in IUnknown::QueryInterface<IDxcBlobEncoding> (this=0x0, pp=0x7ffffffec168) at /home/builder/seta/3rdparty/DirectXShaderCompiler/modified/src/include/dxc/Support/WinAdapter.h:527
#1  0x00000000004483e5 in hlsl::DxcGetBlobAsUtf8 (pBlob=0x0, pBlobEncoding=0x7ffffffecca8) at /home/builder/seta/3rdparty/DirectXShaderCompiler/modified/src/lib/DxcSupport/FileIOHelper.cpp:571
#2  0x00007ffffb985181 in DxcCompiler::CompileWithDebug (this=0x6e91a0, pSource=0x0, pSourceName=0x6e9360 L"TerrainCacheUpdate.cp", pEntryPoint=0x6e94f0 L"main", pTargetProfile=0x6e94c0 L"cs_6_0", pArguments=0x6e9140, argCount=4,
    pDefines=0x7ffffffed578, defineCount=0, pIncludeHandler=0x6e93c0, ppResult=0x7ffffffed0a0, ppDebugBlobName=0x0, ppDebugBlob=0x0)
    at /home/builder/seta/3rdparty/DirectXShaderCompiler/modified/src/tools/clang/tools/dxcompiler/dxcompilerobj.cpp:377
#3  0x00007ffffb98439a in DxcCompiler::Compile (this=0x6e91a0, pSource=0x6e9470, pSourceName=0x6e9360 L"TerrainCacheUpdate.cp", pEntryPoint=0x6e94f0 L"main", pTargetProfile=0x6e94c0 L"cs_6_0", pArguments=0x6e9140, argCount=4,
    pDefines=0x7ffffffed578, defineCount=0, pIncludeHandler=0x6e93c0, ppResult=0x7ffffffed0a0) at /home/builder/seta/3rdparty/DirectXShaderCompiler/modified/src/tools/clang/tools/dxcompiler/dxcompilerobj.cpp:299
#4  0x000000000043cf2c in DxcContext::Compile (this=0x7ffffffedad0) at /home/builder/seta/3rdparty/DirectXShaderCompiler/modified/src/tools/clang/tools/dxc/dxc.cpp:762
#5  0x000000000043ef11 in main (argc=5, argv_=0x7ffffffedc58) at /home/builder/seta/3rdparty/DirectXShaderCompiler/modified/src/tools/clang/tools/dxc/dxc.cpp:1140
```

Compiling without the `-spirv` and/or `-Zi` flags will properly print out `fatal error: 'missing.h' file not found` instead. This behavior is the same for the windows build.

**Comment by ehsannas** [comment]
Hi @tafuri , Thanks for reporting. This issue was fixed yesterday (#1857 )
