### ISSUE TITLE
[spirv] crash when compiling a hull shader

### ISSUE THREAD

**Issue by xxxbxxx** [microsoft/DirectXShaderCompiler#2243]
hi,

when compiling this:
```hlsl
struct HS_QUAD_INPUT {
	float2 Origin: TEXCOORD0;
	float2 Size: TEXCOORD1;
};

struct HS_OUTPUT {
	float Dummy : TEXCOORD0;
};

struct QUAD_PATCH_DATA {
	float Edges[4]: SV_TessFactor;
	float Inside[2]: SV_InsideTessFactor;

	float2 Origin: TEXCOORD0;
	float2 Size: TEXCOORD1;
};


QUAD_PATCH_DATA hsPatchConstant(InputPatch<HS_QUAD_INPUT, 1> Input) {
	return (QUAD_PATCH_DATA)0;

}
[domain("quad")]
[outputtopology("triangle_ccw")]
[partitioning("fractional_odd")]
[outputcontrolpoints(1)]
[patchconstantfunc("hsPatchConstant")]
HS_OUTPUT main(InputPatch<HS_QUAD_INPUT, 1> Input)
{
	return (HS_OUTPUT)0;
}
```

with `dxc -Ths_6_0 hull.hlsl -spirv`

The compiler crashes (it doesn't without -spirv)

backtrace:
```gdb
Program received signal SIGSEGV, Segmentation fault.
#0  0x00007ffff5d91370 in clang::spirv::SpirvInstruction::isNonUniform (this=0x0)
    at ../tools/clang/include/clang/SPIRV/SpirvInstruction.h:165
#1  0x00007ffff5d8c137 in clang::spirv::SpirvBuilder::createAccessChain (this=0x5555558b2f60, resultType=0x5555558b4920,
    base=0x5555558b48b8, indexes=..., loc=...) at ../tools/clang/lib/SPIRV/SpirvBuilder.cpp:275
#2  0x00007ffff5d699e8 in clang::spirv::DeclResultIdMapper::createStageVars (this=0x5555558b30c0,
    sigPoint=0x7ffff7fc6300 <hlsl::SigPoint::ms_SigPoints+160>, decl=0x5555558e0d80, asInput=false, type=..., arraySize=1,
    namePrefix=..., invocationId=..., value=0x7fffffffc5d0, noWriteBack=false, inheritSemantic=0x7fffffffc610)
    at ../tools/clang/lib/SPIRV/DeclResultIdMapper.cpp:2007
#3  0x00007ffff5d6a906 in clang::spirv::DeclResultIdMapper::createStageVars (this=0x5555558b30c0,
    sigPoint=0x7ffff7fc6300 <hlsl::SigPoint::ms_SigPoints+160>, decl=0x5555558e60b0, asInput=false, type=..., arraySize=1,
    namePrefix=..., invocationId=..., value=0x7fffffffc878, noWriteBack=false, inheritSemantic=0x7fffffffc8c0)
    at ../tools/clang/lib/SPIRV/DeclResultIdMapper.cpp:2153
#4  0x00007ffff5d617cf in clang::spirv::DeclResultIdMapper::createStageOutputVar (this=0x5555558b30c0, decl=0x5555558e60b0, arraySize=1,
    invocationId=0x0, storedValue=0x5555558b4788) at ../tools/clang/lib/SPIRV/DeclResultIdMapper.cpp:476
#5  0x00007ffff5d26827 in clang::spirv::SpirvEmitter::emitEntryFunctionWrapper (this=0x5555558b2c90, decl=0x5555558e60b0,
    entryFuncInstr=0x5555558b3e28) at ../tools/clang/lib/SPIRV/SpirvEmitter.cpp:10195
#6  0x00007ffff5cfa9f9 in clang::spirv::SpirvEmitter::doFunctionDecl (this=0x5555558b2c90, decl=0x5555558e60b0)
    at ../tools/clang/lib/SPIRV/SpirvEmitter.cpp:1012
#7  0x00007ffff5cf90c0 in clang::spirv::SpirvEmitter::doDecl (this=0x5555558b2c90, decl=0x5555558e60b0)
    at ../tools/clang/lib/SPIRV/SpirvEmitter.cpp:716
#8  0x00007ffff5cf8705 in clang::spirv::SpirvEmitter::HandleTranslationUnit (this=0x5555558b2c90, context=...)
    at ../tools/clang/lib/SPIRV/SpirvEmitter.cpp:601
#9  0x00007ffff5e434f2 in clang::ParseAST (S=..., PrintStats=false, SkipFunctionBodies=false)
    at ../tools/clang/lib/Parse/ParseAST.cpp:160
#10 0x00007ffff5070e23 in clang::ASTFrontendAction::ExecuteAction (this=0x7fffffffd3c0)
    at ../tools/clang/lib/Frontend/FrontendAction.cpp:554
#11 0x00007ffff50708ec in clang::FrontendAction::Execute (this=0x7fffffffd3c0) at ../tools/clang/lib/Frontend/FrontendAction.cpp:455
#12 0x00007ffff4606076 in DxcCompiler::CompileWithDebug (this=0x555555878d90, pSource=0x555555857340,
    pSourceName=0x555555879270 L"hull.hlsl", pEntryPoint=0x555555878fd0 L"main", pTargetProfile=0x555555878f80 L"hs_6_0",
    pArguments=0x555555857390, argCount=3, pDefines=0x7fffffffe218, defineCount=0, pIncludeHandler=0x555555878f50,
    ppResult=0x7fffffffdd58, ppDebugBlobName=0x0, ppDebugBlob=0x0) at ../tools/clang/tools/dxcompiler/dxcompilerobj.cpp:693
#13 0x00007ffff46042e2 in DxcCompiler::Compile (this=0x555555878d90, pSource=0x555555857340, pSourceName=0x555555879270 L"hull.hlsl",
    pEntryPoint=0x555555878fd0 L"main", pTargetProfile=0x555555878f80 L"hs_6_0", pArguments=0x555555857390, argCount=3,
    pDefines=0x7fffffffe218, defineCount=0, pIncludeHandler=0x555555878f50, ppResult=0x7fffffffdd58)
    at ../tools/clang/tools/dxcompiler/dxcompilerobj.cpp:450
#14 0x00005555555f1998 in DxcContext::Compile (this=0x7fffffffdf20) at ../tools/clang/tools/dxc/dxclib/dxc.cpp:785
#15 0x00005555555f3c4f in dxc::main (argc=4, argv_=0x7fffffffe928) at ../tools/clang/tools/dxc/dxclib/dxc.cpp:1170
#16 0x00005555555ee259 in main (argc=4, argv_=0x7fffffffe928) at ../tools/clang/tools/dxc/dxcmain.cpp:20
```

**Comment by ehsannas** [comment]
Thanks for reporting @xxxbxxx ! I'll investigate

**Comment by xxxbxxx** [comment]
additionally, fixing the function prototype:
```diff
-HS_OUTPUT main(InputPatch<HS_QUAD_INPUT, 1> Input)
+HS_OUTPUT main(InputPatch<HS_QUAD_INPUT, 1> Input, uint iPoint : SV_OutputControlPointID)
```
fixes the compiler crash.

**Comment by ehsannas** [comment]
Our code had assumed that every hull shader comes with a ControlPointID. 
We then perform the "main" function once for every control point (with ControlPointID). Then we place an execution barrier to make sure all of those are finished. We then execute the "PatchConstantFunction" only once. (use [this](https://docs.microsoft.com/en-us/windows/win32/direct3d11/direct3d-11-advanced-stages-hull-shader-design) as a guide)

I'm wondering what is the right behavior when no ControlPointID is provided?

**Comment by ehsannas** [comment]
I have fixed the crash, so that at least the user sees the proper error message (PR #2568 )
