### ISSUE TITLE
Segfault compiling simple shader

### ISSUE THREAD

**Issue by expipiplus1** [microsoft/DirectXShaderCompiler#6926]
**Description**

DXC segfaults in llvm compiling this simple compute shader.

**Steps to Reproduce**
```hlsl
[numthreads(1, 1, 1)]
void computeMain()
{
    int i = 0;
    for(;;)
    {
        int _S5;
        if(i > 0)
            break;
        i++;
    }
}
```

`dxc -T cs_6_8 -E computeMain a.hlsl`

**Actual Behavior**
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff750d0ee in void llvm::visitAll<(anonymous namespace)::SCEVSearch>(llvm::SCEV const*, (anonymous namespace)::SCEVSearch&) [clone .constprop.0] () from /nix/store/3gpnjc41mg14mrz8dvvwwqzippx46c0n-directx-shader-compiler-1.8.2407/lib/libdxcompiler.so
(gdb) bt
#0  0x00007ffff750d0ee in void llvm::visitAll<(anonymous namespace)::SCEVSearch>(llvm::SCEV const*, (anonymous namespace)::SCEVSearch&) [clone .constprop.0] ()
   from /nix/store/3gpnjc41mg14mrz8dvvwwqzippx46c0n-directx-shader-compiler-1.8.2407/lib/libdxcompiler.so
#1  0x00007ffff750d9fe in llvm::ScalarEvolution::forgetMemoizedResults(llvm::SCEV const*) () from /nix/store/3gpnjc41mg14mrz8dvvwwqzippx46c0n-directx-shader-compiler-1.8.2407/lib/libdxcompiler.so
#2  0x00007ffff750dba9 in llvm::SCEVUnknown::deleted() () from /nix/store/3gpnjc41mg14mrz8dvvwwqzippx46c0n-directx-shader-compiler-1.8.2407/lib/libdxcompiler.so
#3  0x00007ffff6318ac2 in llvm::ValueHandleBase::ValueIsDeleted(llvm::Value*) () from /nix/store/3gpnjc41mg14mrz8dvvwwqzippx46c0n-directx-shader-compiler-1.8.2407/lib/libdxcompiler.so
#4  0x00007ffff63191cd in llvm::Value::~Value() () from /nix/store/3gpnjc41mg14mrz8dvvwwqzippx46c0n-directx-shader-compiler-1.8.2407/lib/libdxcompiler.so
#5  0x00007ffff62ddc83 in llvm::PHINode::~PHINode() () from /nix/store/3gpnjc41mg14mrz8dvvwwqzippx46c0n-directx-shader-compiler-1.8.2407/lib/libdxcompiler.so
#6  0x00007ffff6298236 in llvm::BasicBlock::~BasicBlock() () from /nix/store/3gpnjc41mg14mrz8dvvwwqzippx46c0n-directx-shader-compiler-1.8.2407/lib/libdxcompiler.so
#7  0x00007ffff62997aa in llvm::BasicBlock::eraseFromParent() () from /nix/store/3gpnjc41mg14mrz8dvvwwqzippx46c0n-directx-shader-compiler-1.8.2407/lib/libdxcompiler.so
#8  0x00007ffff62d8e14 in llvm::Function::dropAllReferences() () from /nix/store/3gpnjc41mg14mrz8dvvwwqzippx46c0n-directx-shader-compiler-1.8.2407/lib/libdxcompiler.so
#9  0x00007ffff6305fc0 in llvm::Module::dropAllReferences() () from /nix/store/3gpnjc41mg14mrz8dvvwwqzippx46c0n-directx-shader-compiler-1.8.2407/lib/libdxcompiler.so
#10 0x00007ffff6306143 in llvm::Module::~Module() () from /nix/store/3gpnjc41mg14mrz8dvvwwqzippx46c0n-directx-shader-compiler-1.8.2407/lib/libdxcompiler.so
#11 0x00007ffff685338c in clang::CodeGenAction::~CodeGenAction() () from /nix/store/3gpnjc41mg14mrz8dvvwwqzippx46c0n-directx-shader-compiler-1.8.2407/lib/libdxcompiler.so
#12 0x00007ffff6226372 in DxcCompiler::Compile(DxcBuffer const*, wchar_t const**, unsigned int, IDxcIncludeHandler*, GUID const&, void**) () from /nix/store/3gpnjc41mg14mrz8dvvwwqzippx46c0n-directx-shader-compiler-1.8.2407/lib/libdxcompiler.so
#13 0x00007ffff6219d1a in hlsl::DxcCompilerAdapter::WrapCompile(bool, IDxcBlob*, wchar_t const*, wchar_t const*, wchar_t const*, wchar_t const**, unsigned int, DxcDefine const*, unsigned int, IDxcIncludeHandler*, IDxcOperationResult**, wchar_t**, IDxcBlob**)
    () from /nix/store/3gpnjc41mg14mrz8dvvwwqzippx46c0n-directx-shader-compiler-1.8.2407/lib/libdxcompiler.so
#14 0x00007ffff621aa52 in hlsl::DxcCompilerAdapter::Compile(IDxcBlob*, wchar_t const*, wchar_t const*, wchar_t const*, wchar_t const**, unsigned int, DxcDefine const*, unsigned int, IDxcIncludeHandler*, IDxcOperationResult**) ()
   from /nix/store/3gpnjc41mg14mrz8dvvwwqzippx46c0n-directx-shader-compiler-1.8.2407/lib/libdxcompiler.so
#15 0x0000000000417a97 in DxcContext::Compile() ()
#16 0x000000000040d120 in dxc::main(int, char const**) ()
#17 0x00007ffff5a3314e in __libc_start_call_main () from /nix/store/5adwdl39g3k9a2j0qadvirnliv4r7pwd-glibc-2.39-52/lib/libc.so.6
#18 0x00007ffff5a33209 in __libc_start_main_impl () from /nix/store/5adwdl39g3k9a2j0qadvirnliv4r7pwd-glibc-2.39-52/lib/libc.so.6
#19 0x000000000040e405 in _start ()
```

**Environment**
- reproduces on `libdxcompiler.so: 1.8(dev;4302-7c158783)` and `1.8.2405`
- Host Operating System NixOS

**Comment by damyanp** [comment]
I cannot repro this: https://godbolt.org/z/jhjcW9YqY
